### ISSUE TITLE
你好,你的这个如何访问页面呢?

### ISSUE THREAD

**Issue by pangao66** [duenyang/webpack-template#1]
我用了你的这个, npm run dev 没有报错, 可是怎么访问页面呢?http://localhost:8080/a 这样都不对

**Comment by pangao66** [comment]
你好, 编辑html 文件页面不能自动刷新

**Comment by duenyang** [comment]
http://localhost:8080/a

**Comment by duenyang** [comment]
http://localhost:8080/a.html
